import { StructuredForm } from '@/components/homepage/structured-form';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { router } from '@inertiajs/react';
type LinkRow={id:number;audience:string;label:string;href:string;sort_order:number;is_active:boolean};
export default function NavbarEdit({ record,links=[] }: { record: Record<string, string>;links:LinkRow[] }) {
 function save(e:React.FormEvent<HTMLFormElement>,id?:number){e.preventDefault();const data=new FormData(e.currentTarget);data.set('is_active',data.get('is_active')?'1':'0');if(id)data.set('_method','PUT');router.post(`/cms/homepage/navbar/links${id?`/${id}`:''}`,data);}
 return <><StructuredForm title="Navbar Settings" action="/cms/homepage/navbar" record={record} fields={[{name:'logo',label:'Logo',type:'file'},{name:'logo_alt',label:'Logo alt text'},{name:'logo_href',label:'Logo redirect'},{name:'book_label',label:'Book button label'},{name:'book_href',label:'Book button redirect'},{name:'mobile_eyebrow',label:'Sidebar eyebrow'},{name:'mobile_open_label',label:'Open menu label'},{name:'mobile_close_label',label:'Close menu label'}]}/><div className="mx-auto max-w-4xl space-y-4 p-6"><h2 className="text-xl font-semibold">Desktop and Mobile Links</h2>{[...links,undefined].map((link,index)=><form key={link?.id??'new'} onSubmit={e=>save(e,link?.id)} className="grid gap-3 rounded-md border p-4 md:grid-cols-5"><div><Label>Audience</Label><select name="audience" defaultValue={link?.audience??'desktop'} className="h-10 w-full rounded-md border bg-background px-2"><option value="desktop">Desktop</option><option value="mobile">Mobile sidebar</option></select></div><div><Label>Label</Label><Input name="label" defaultValue={link?.label}/></div><div><Label>Redirect</Label><Input name="href" defaultValue={link?.href}/></div><div><Label>Order</Label><Input name="sort_order" type="number" defaultValue={link?.sort_order??index}/><label className="mt-2 flex gap-2 text-sm"><input name="is_active" type="checkbox" defaultChecked={link?.is_active??true}/> Active</label></div><div className="flex items-end gap-2"><Button>{link?'Save':'Add'}</Button>{link&&<Button type="button" variant="destructive" onClick={()=>router.delete(`/cms/homepage/navbar/links/${link.id}`)}>Delete</Button>}</div></form>)}</div></>;
}
